-- bottleID, name, style, distillerID, bottlerID
INSERT INTO Bottle VALUES ('1', 'Maker''s Mark Bourbon', 'Straight Bourbon','1',NULL);
INSERT INTO Bottle VALUES ('2', 'Redbreast 12', 'Single Pot Still','2',NULL);
INSERT INTO Bottle VALUES ('3', 'Silver Whiskey Western Oat','Light Whiskey','3',NULL);
INSERT INTO Bottle VALUES ('4', 'Whiskey Del Bac Classic','Single Malt','4',NULL);
INSERT INTO Bottle VALUES ('5', 'Whiskey Del Bac Dorado','Single Malt','4',NULL);
INSERT INTO Bottle VALUES ('6', 'Double Rye!','Blended Straight Rye','11','2');
INSERT INTO Bottle VALUES ('7', 'Shieldaig 12','Speyside',NULL,'3');
INSERT INTO Bottle VALUES ('8', 'Witherspoon''s Straight Bourbon','Straight Bourbon','6',NULL);
INSERT INTO Bottle VALUES ('9', 'Glenfiddich 12','Speyside','7',NULL);
INSERT INTO Bottle VALUES ('10', 'Glenmorangie Original','Highland','8',NULL);
INSERT INTO Bottle VALUES ('11', 'Copper Pony Rye','Rye','9',NULL);
INSERT INTO Bottle VALUES ('12', 'Laphroaig 10','Islay','10',NULL);
INSERT INTO Bottle VALUES ('13', 'George Dickel Rye Whisky','Rye','11','1');
INSERT INTO Bottle VALUES ('14', 'Winchester Straight Bourbon','Straight Bourbon','9',NULL);
INSERT INTO Bottle VALUES ('15', 'Rendezvous Rye','Blended Straight Rye','11','2');
INSERT INTO Bottle VALUES ('16', 'Wyoming Whiskey','Small Batch Bourbon','12',NULL);
INSERT INTO Bottle VALUES ('17', 'Four Roses Single Barrel','Straight Bourbon','13',NULL);
INSERT INTO Bottle VALUES ('18', 'Tullamore D.E.W.','Blended Irish','14',NULL);
INSERT INTO Bottle VALUES ('19', 'Oban 14','Highland','15',NULL);
INSERT INTO Bottle VALUES ('20', 'Pig''s Nose','Blended Scotch',NULL,'4');
